site_name: PayOpt


nav:
  - Home: index.md
  - API: API.md
  - DB: DB.md
  - Model: Model.md


plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]


theme: 
  name: readthedocs